FROM kameshsampath/fedora

MAINTAINER Kamesh Sampath, kamesh.sampath@hotmail.com

# Update 
RUN yum -y update

# Install JRE 7
# RUN yum -y install java-1.7.0-openjdk
  RUN yum -y install java-1.7.0-openjdk-headless
