FROM kameshsampath/ubuntu

MAINTAINER Kamesh Sampath, kamesh.sampath@hotmail.com

# Update the APT cache
RUN apt-get update
RUN apt-get upgrade -y

# Install JDK 7
RUN apt-get -q -y install openjdk-7-jdk
